title: Jake Mammen, MS # your name (or website title) here
logo: "/images/62113268_842339089456367_5892535769645449216_n.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Hi, my name is Jake Mammen and I'm the Director of Situational Awareness for an All Hazard Critical Event Managment Company called Early Alert. 
  I manage the Situational Awareness Department and Watch Office, which provides 24/7 situational awareness to Early Alert's client footprint across the globe. 
  In addition, I manage and maintain various GIS tools and applications used to carry out daily operations. 
  GIS is something I am very passionate about and not only is it something I enjoy learning, but it plays an important role in keeping our clientele safe. I'm an avid football fan, love the outdoors, and enjoy traveling across the country!
  <br><br>
  <a href="https://www.linkedin.com/in/jake-mammen-ms-784961196/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
