title: Jake Mammen # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  Hi, my name is Jake Mammen and I'm the Director of Situational Awarness for an Emergency Management Company called Early Alert. 
  I manage the Watch Office, which provides 24/7 situational awareness to our clients. 
  In addition, I manage and maintain various GIS tools used to carry out daily operations. 
  GIS is something I’ve very passionate about and not only does it allow me to enjoy what I do, but it plays an important role in keeping our clients safe.
  <br><br>
  Second description
  I'm an avid football fan, love the outdoors, and enjoy traveling across the country!
  <br><br>
  <a href="https://www.linkedin.com/in/jake-mammen-784961196/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
